# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat', '0002_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hash',
            field=models.TextField(default=1, verbose_name='Hash text'),
            preserve_default=False,
        ),
    ]
